# Generated by Django 4.2.8 on 2023-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivelir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(upload_to='static/jewelry_images/'),
        ),
    ]
